name: Github Actions Demo
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{github.event_name}} event."
      - run: echo "The job was now running on a ${{runner.os}} server hosted by GitHub!"
      - run: echo "The name of your branch is  ${{github.ref}} and your repository is ${{github.repository}}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{github.repository}} repository has been cloned to the runner" 